name: Activity CI Job

on:
  push:
    branches:
      - main 

  pull_request:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Install packages
        run: npm install

      - name: Run all tests
        run: npm test