name: Activity CI Job

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: npm install

      - name: Run all tests
        run: |
          mkdir -p test-results
          npm test > test-results/results.txt

      - name: Zip test results
        run: zip -r test_results.zip test-results

      - name: Upload test results artifact
        uses: actions/upload-artifact@v3
        with:
          name: test_results
          path: test_results.zip